### ISSUE TITLE
Devtools

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/query#1]
Add https://tanstack.com/query/v4/docs/devtools

**Comment by nhducit** [comment]
Do you have any ideas to integrate the devtool? I think there are 2 ways
- create a wrapper for the Devtool - written in React - e.g. create a react app to host devtool
+ pros:
++ reuse the react-query UI
++ less effort to maintain the devtool
+ cons: I cannot think of any issue now

- rewrite the devtool UI in angular
+ pros: 
++ maybe the devtool integration feel more Angular-ish

+ cons:
++ more efforts to rewrite the UI
++ need t

**Comment by NetanelBasal** [comment]
Because it's only a dev tool, we can start with the first option. You can try the technique described here:

https://netbasal.com/using-react-in-angular-applications-1bb907ecac91

**Comment by nhducit** [comment]
thanks @NetanelBasal I will check that document

**Comment by nhducit** [comment]
here is the plan I have now
- create an angular wrapper for react-query devtool
- exclude devtool source code from the production bundle, maybe we can use this [ng-cli feature](https://angular.io/guide/build#configure-environment-specific-defaults)

**Comment by NetanelBasal** [comment]
The consumer will add `if(env.production)` and it'll remove it from the prod bundle.

**Comment by nhducit** [comment]
TIL, do you have any resource to learn more about `if(env.production)`. I cannot find any think relate to it


this is the only way I know
```
{
  ...
  "projects": {
    ...
    "configurations": {
      "production": {
        ...
        "fileReplacements": [
          ...
          *** ADD YOUR REPLACEMENT FILES HERE ***
          ...
        ]
      }
    }
  }
}
```

**Comment by NetanelBasal** [comment]
https://netbasal.com/environment-based-dead-code-elimination-in-angular-54eec1f92a65

**Comment by nhducit** [comment]
it's working

<img width="766" alt="CleanShot 2022-10-07 at 15 35 57@2x" src="https://user-images.githubusercontent.com/4246176/194510665-8f284d13-7322-4486-96d3-700326700b5b.png">

**Comment by NetanelBasal** [comment]
Cool
