### ISSUE TITLE
TanStack Query v5 support

### ISSUE THREAD

**Issue by Timebutt** [ngneat/query#116]
### Which @ngneat/query-* package(s) are relevant/releated to the feature request?

query

### Description

TanStack Query v5 released last week ([announcement](https://tanstack.com/blog/announcing-tanstack-query-v5) - [release page](https://github.com/TanStack/query/releases/tag/v5.0.0)). v5 brings some awesome new improvements that I'm sure many of us can't wait to get started with!

I'm creating this issue for transparency so the community can track progress on this upgrade, well knowing the actual implementation might take some time to realize ;)

### Proposed solution

Upgrade this repository to v5. I'm not sure if this is something you usually do yourself or if you are accepting community PRs?

### Alternatives considered

Well, this package will have to support v5 at some point so not sure there really is an alternative ;)

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Hi, I would love to see a PR. The typed needs to be updated as they switch to one object signature.

**Comment by luii** [comment]
@NetanelBasal Hey, im currently on this issue and the last two problems im having is the incompatibility of the options, specifically the Error Types. Btw. if you want you can assign me this issue, if i got these problems resolved im testing it and create a PR for it.

![grafik](https://github.com/ngneat/query/assets/8077014/582e928d-bb60-44d2-a12a-8ff52be1ccea)

Do you have any idea how this could be fixed?

**Comment by luii** [comment]
Just for the contexts: i removed the overloads for the `use` function and since tanstack doesnt exports `parseQueryArgs` anymore i also removed that.

**Comment by NetanelBasal** [comment]
@luii I will do it together with some refactoring and maybe will add a signal option.

**Comment by luii** [comment]
@NetanelBasal if you're not already on it i can try the Mutation API. Do you have something specific in mind that we should do for that?

If you're already on it then im continuing with the Documentation i'd say

**Comment by netanel-utila** [comment]
You can continue with the mutation API. Use the same line as the query.

**Comment by NetanelBasal** [comment]
Coming next week

**Comment by NetanelBasal** [comment]
v2.0.0-beta.0 was released. Feel free to test it :)
