### ISSUE TITLE
Sync `mutate` function is missing the mutation options as parameter

### ISSUE THREAD

**Issue by luii** [ngneat/query#134]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

No

### Description

The sync `mutate` function is missing the options as parameter, thus any callback for example wont be called.

### Please provide a link to a minimal reproduction of the bug

-

### Please provide the environment you discovered this bug in

```true
https://github.com/ngneat/query/blob/main/query/src/lib/mutation.ts#L104
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Thanks, already fixed it :)

**Comment by NetanelBasal** [comment]
@luii I'm pushing now a starter of tests if you want to continue let me know

**Comment by luii** [comment]
@NetanelBasal having alot of work lately, i try to squeeze something in if i have time

**Comment by NetanelBasal** [comment]
Sure, I've added the initial boilerplate for the tests and example in query.spec.ts
