### ISSUE TITLE
Cannot find module '@tanstack/query-core/build/legacy/queryClient-b7fce2ff'

### ISSUE THREAD

**Issue by instantgis** [ngneat/query#151]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

No

### Description

out of the box version 2.0.0-beta.10 
npm i @ngneat/query

### Please provide the exception or error you saw

```true
Error: node_modules/@ngneat/query/lib/query-options.d.ts:21:275 - error TS2307: Cannot find module '@tanstack/query-core/build/legacy/queryClient-b7fce2ff' or its corresponding type declarations.

21 export declare function normalizeOptions<TQueryFnData, TError, TData, TQueryData, TQueryKey extends QueryKey, TPageParam = never>(client: QueryClient, options: QueryObserverOptions<TQueryFnData, TError, TData, TQueryData, TQueryKey, TPageParam>, injector: Injector): import("@tanstack/query-core/build/legacy/queryClient-b7fce2ff").L<unknown, Error, unknown, unknown, QueryKey>;
```

### Please provide the environment you discovered this bug in

```true
Angular core ^17.0.4 app
"@ngneat/query": "^2.0.0-beta.10"
```

### Anything else?

I like the concept. This is beta so anything is possible right? 
Id like this to work. Is there a known working prior version? 

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
We're using 2.0.0-beta.10 and doesn't have this error. Can you try to delete your node modules and try again?

**Comment by pavankjadda** [comment]
> We're using 2.0.0-beta.10 and doesn't have this error. Can you try to delete your node modules and try again?

We see this error as well. Here is the reproducible repo
Github: https://github.com/pavankjadda/ngneat-query-151
Stackblitz: https://stackblitz.com/~/github.com/pavankjadda/ngneat-query-151
