### ISSUE TITLE
Add refetch to intersectResults

### ISSUE THREAD

**Issue by Zacherl** [ngneat/query#162]
### Which @ngneat/query-* package(s) are relevant/releated to the feature request?

query

### Description

I tried using the intersectResults utility to combine to results of different queries, e. g.:

```typescript
intersectResults({projects: ..., users: ...}, ({projects, users}) => ({projects, users}));
```

I also wanted to refresh both queries at the same point in time, however, iIn the implementation here the refresh functionality is omitted when intersecting query results. I implemented a workaround on a subset of the QueryObserverResult that is working good enough for our use case.

Would you be interested to integrate such a change?

### Proposed solution

```typescript
type SubsetKeys = 'data' | 'isError' | 'isFetching' | 'isStale';

export type QueryObserverResultSubset<T = unknown> = Pick<QueryObserverResult<T>, SubsetKeys> & {
  refetch: () => Promise<QueryObserverResultSubset<T>>;
};

type SignalDictionary = Record<string, Signal<QueryObserverResult<any>>>;
type ResultDictionary<T> = {
  [K in keyof T]: T[K] extends Signal<QueryObserverResult<infer R>> ? QueryObserverResult<R> : never;
};
type Result<T> = {
  [K in keyof T]: T[K] extends Signal<QueryObserverResult<infer R>> ? R : never;
};

export function mergeQueries<T extends SignalDictionary>(signals: T): Signal<QueryObserverResult<Result<T>>> {
  return computed(() => {
    const resultsByKey = mapValues(signals, signal => signal()) as ResultDictionary<T>;
    return mergeQueryResults(resultsByKey) as QueryObserverResult<Result<T>>;
  });
}

function mergeQueryResults(
  resultsByKey: Record<string, QueryObserverResult>,
): QueryObserverResultSubset<Record<string, unknown>> {
  const data: Record<string, unknown> = {};
  for (const [key, result] of Object.entries(resultsByKey)) {
    data[key] = result.data;
  }

  const results = Object.values(resultsByKey);
  return {
    data: Object.values(data).every(isDefined) ? data : undefined,
    isError: results.some(({ isError }) => isError),
    isFetching: results.some(({ isFetching }) => isFetching),
    isStale: results.some(({ isStale }) => isStale),
    refetch: () => refetch(resultsByKey),
  };
}

async function refetch(
  resultsByKey: Record<string, QueryObserverResult>,
): Promise<QueryObserverResultSubset<Record<string, unknown>>> {
  const results = await Promise.all(
    Object.entries(resultsByKey).map(([key, result]) =>
      result.refetch().then(result => ({
        key,
        result,
      })),
    ),
  );
  return mergeQueryResults(results.reduce((acc, { key, result }) => ({ ...acc, [key]: result }), {}));
}
```

### Alternatives considered

See the proposed solution.

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
I'm currently grappling with the complete grasp of the issue and its corresponding solution. It would greatly aid my understanding if you could provide two StackBlitz instances: one illustrating the current behavior along with any missing functionalities, and a second one showcasing your proposed solution in action.

**Comment by Zacherl** [comment]
Sure! My workaround contains a lot of code that is not really important. The major point is that I also proxied the refetch function in the result.

Here is an example:
https://stackblitz.com/edit/stackblitz-starters-kwhcvj?file=src%2Fmain.ts
Does this help?

**Comment by Zacherl** [comment]
Exactly. 🙈

**Comment by NetanelBasal** [comment]
Sure, you're welcome to submit a PR. Note that you probably only need to run the Promise.all function without returning any values and it will work the same.

**Comment by Zacherl** [comment]
I added a pull request. I did not add a unit test since I did not find any unit tests for the signals.ts file - is this correct?

Just tell me if I should change something!
