### ISSUE TITLE
mutate function should subscribe to mutationObserver

### ISSUE THREAD

**Issue by elmarvr** [ngneat/query#165]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

Yes

### Description

mutation function should subscribe to mutationObserver. Right now callbacks in mutate function are not being called. See @tanstack/query implementation

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
I'm not sure what you mean, but you're welcome to create a PR
