### ISSUE TITLE
onSuccess is never triggered when passed as option to mutate

### ISSUE THREAD

**Issue by pkfms** [ngneat/query#173]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

Yes

### Description

When passing options to the mutate function, onSuccess, onError and onSettled functions are never called.
Please see the stackblitz example. Press the add button to trigger a mutation. The logs from the onSuccess in the service are visible, but the logs from the component are not visible.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-x2kvfi?file=src%2Fmain.ts

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
I'm pretty sure that we fixed it and it was worked. You're welcome to create a PR

**Comment by pkfms** [comment]
Turns out I didn't subscribe to mutation result$ anywhere. Doing that, everything works as expected
