### ISSUE TITLE
support: angular v18

### ISSUE THREAD

**Issue by rbalet** [ngneat/query#179]
### Description

Support to angular v18 would be beautiful

### Proposed solution

-

### Alternatives considered

-

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Give it to me, baby

**Comment by rbalet** [comment]
@NetanelBasal I'd be glad, I just tested and got an  `This command is not available when running the Angular CLI outside a workspace` '^^

**Comment by NetanelBasal** [comment]
Nx

**Comment by luii** [comment]
@rbalet if you run things like `ng serve` inside a `nx` workspace you will get the message you provided. instead of running it with `ng` you need to use `[npx] nx serve <app-name>` (npx only if you dont install it locally/globally on your pc)
