### ISSUE TITLE
bug: `throwOnError` does not work

### ISSUE THREAD

**Issue by robingenz** [ngneat/query#180]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

Yes

### Description

The `throwOnError` option is ignored in the following call:

```ts
this.#query({
  queryKey: ['tasks', '5'],
  queryFn: () => {
    throw new Error('Task not found');
  },
  retry: false,
  throwOnError: true,
});
```

No error is thrown.

### Anything else?

I've already reported this bug in https://github.com/TanStack/query/issues/7022 and a fix was published for `@tanstack/angular-query-experimental`.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
What is the use case for this?

**Comment by robingenz** [comment]
In my case, I want to trigger the global error handler when an error occurs in `queryFn`. Regardless, I expect every tanstack query option to be supported by this library.

**Comment by NetanelBasal** [comment]
Note that in our case, because we're using observables, it will be call observer.error() which both triggers the global handler and the subscriber.error callback.

**Comment by robingenz** [comment]
You mean it should already be working? What am I doing wrong then?

**Comment by NetanelBasal** [comment]
No. I just mentioned what will be the new behaviour. I'll be release asap.

**Comment by robingenz** [comment]
Alright, thank you!
