### ISSUE TITLE
Error: NG0203 at assertInInjectionContext

### ISSUE THREAD

**Issue by timsar2** [ngneat/query#186]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

Yes

### Description

Calling signal value from mutate object inside the html part has error, But if we define the signal part inside the ts file
there is no erro:

```
addTodo = inject(TodosService).addTodo()
// addTodoSignal = this.addTodoSignal.result   <<---- uncomment me so the error will be gone

@if (addTodo.result(); as result) {
      @if (result.isLoading) {
        <p>Mutation is loading</p>
      }
      @if (result.isSuccess) {
        <p>Mutation was successful</p>
      }
      @if (result.isError) {
        <p>Mutation encountered an Error</p>
      }
    }
```

### Please provide the exception or error you saw

```true
Error: NG0203
    at assertInInjectionContext (core.mjs:3441:15)
    at toSignal (rxjs-interop.mjs:174:70)
    at get result (ngneat-query.mjs:366:44)
```

### Do you want to create a pull request?

No

**Comment by luii** [comment]
Please provide a link to a stackblitz with your current setup

**Comment by luii** [comment]
@timsar2 We need more Information e.g. a repository/stackblitz (for reproduction) to appropriatly work on this issue.

**Comment by timsar2** [comment]
seems it is ok with angular 18.0.0
