### ISSUE TITLE
Upgrade the library to Angular 19

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/query#199]
### Description

Upgrade the library to Angular 19

### Proposed solution

Upgrade the library to Angular 19

### Alternatives considered

Upgrade the library to Angular 19

### Do you want to create a pull request?

No

**Comment by Drunkenpilot** [comment]
Got an issue after installed @angular /code@19.0.5

npm warn Could not resolve dependency:
npm warn peer @angular/core@">=16.0.0 <=19.0.4" from @ngneat/query@3.1.0
npm warn node_modules/@ngneat/query
npm warn   @ngneat/query@"^3.1.0" from the root project
