### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/query#23]
Cypress

**Comment by zarghamkhandev** [comment]
I would like to setup tests, but will need more details, like what kind of tests, I can only think of unit tests for source code. @NetanelBasal

**Comment by NetanelBasal** [comment]
Yes, but we can also add Cypress tests for our playground pages.

**Comment by zarghamkhandev** [comment]
sounds interesting, I would like to do this.

**Comment by NetanelBasal** [comment]
@zarghamkhandev, any progress here? We want to go out with the beta next week :)

**Comment by zarghamkhandev** [comment]
@NetanelBasal will get this done this weekend 💯
