### ISSUE TITLE
Add examples to our playground

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/query#30]
### Description

Take one or more of the following examples, create an issue, and assign it to yourself:

- [x] Default Query Function (https://tanstack.com/query/v4/docs/examples/react/default-query-function) #31 
- [x] Prefetching (https://tanstack.com/query/v4/docs/examples/react/prefetching)
- [x] Star Wars (https://tanstack.com/query/v4/docs/examples/react/star-wars) #37 
- [x] Rick Morty (https://tanstack.com/query/v4/docs/examples/react/rick-morty) #38
- [ ] Playground (https://tanstack.com/query/v4/docs/examples/react/playground) #43
- [x] Optimistic Updates (https://tanstack.com/query/v4/docs/examples/react/optimistic-updates-typescript) #44 
- [ ] Auto Refetching (https://tanstack.com/query/v4/docs/examples/react/auto-refetching)
- [ ] Placeholder data (https://tanstack.com/query/v4/docs/guides/placeholder-query-data)
- [ ] Initial data (https://tanstack.com/query/v4/docs/guides/initial-query-data)
- [ ] Table with server side filters and sorting
### Proposed solution

-

### Alternatives considered

-

### Do you want to create a pull request?

No

**Comment by ronnyek** [comment]
I see optimistic updates as being checked here... is this documentation I should be able to see somewhere? Is this functionality already implemented in the library?
