### ISSUE TITLE
Default Query Function example

### ISSUE THREAD

**Issue by hrvbernardic** [ngneat/query#31]
### Which @ngneat/query-* package(s) are relevant/releated to the feature request?

query

### Description

https://tanstack.com/query/v4/docs/examples/react/default-query-function

### Proposed solution

-

### Alternatives considered

-

### Do you want to create a pull request?

Yes

**Comment by hrvbernardic** [comment]
Either I am doing something wrong or I can't assign myself. @NetanelBasal

**Comment by NetanelBasal** [comment]
Done
