### ISSUE TITLE
Optimistic exemple playground

### ISSUE THREAD

**Issue by tomalaforge** [ngneat/query#44]
### Description

Implements Optimistic exemple in playground

### Proposed solution

https://tanstack.com/query/v4/docs/examples/react/optimistic-updates-typescript)

### Alternatives considered

None

### Do you want to create a pull request?

No

**Comment by tomalaforge** [comment]
Can you assigned it to me, please ? Thx

**Comment by NetanelBasal** [comment]
Done

**Comment by NetanelBasal** [comment]
Sure you can take it

**Comment by tomalaforge** [comment]
yes you can I have so much to do. Thanks @JoaoPauloLousada

**Comment by JoaoPauloLousada** [comment]
https://github.com/ngneat/query/pull/74
