### ISSUE TITLE
Better support for constructor based injection for QueryClient, QueryProvider, MutationProvider and so on

### ISSUE THREAD

**Issue by Den-dp** [ngneat/query#48]
### Which @ngneat/query-* package(s) are relevant/releated to the feature request?

query

### Description

The following right now is not possible:
```ts
@Injectable({ providedIn: 'root' })
export class TodosService {
  constructor(
    private http: HttpClient,
    private queryClient: QueryClient,
    private useQuery: QueryProvider,
    private useMutation: MutationProvider
  ) {}
}
```
cause of the error:
```
No suitable injection token for parameter 'queryClient' of class 'TodosService'.
  Consider using the @Inject decorator to specify an injection token.
```

The following also requires types:
```ts
@Injectable({ providedIn: 'root' })
export class TodosService {
  constructor(
    private http: HttpClient,
    @Inject(QueryClient) private queryClient: QueryClient,
    @Inject(QueryProvider) private useQuery: QueryProvider,
    @Inject(MutationProvider) private useMutation: MutationProvider
  ) {}
}
```
and fails with this error:
```
'QueryClient' refers to a value, but is being used as a type here. Did you mean 'typeof QueryClient'?ts(2749)
```
proposed `typeof QueryClient` doesn't work too cause of 
```
Property 'invalidateQueries' does not exist on type 'InjectionToken<QueryClient>'.ts(2339)
```

### Proposed solution

Not sure if there is a simple solution

### Alternatives considered

The only solution that works for now is:
```ts
@Injectable({ providedIn: 'root' })
export class TodosService {
  private http = inject(HttpClient);
  private queryClient = inject(QueryClient);
  private useQuery = inject(QueryProvider);
  private useMutation = inject(MutationProvider);
}
```

### Do you want to create a pull request?

No

**Comment by Den-dp** [comment]
After a brief investigation, I started to think that this might be solved by changing f.e. this:
https://github.com/ngneat/query/blob/c67c80266fcc1a9f9bdd404d4177757a456c6548/packages/ng-query/src/lib/query-client.ts#L5-L21
in the following way:
```ts
@Injectable({
  provideIn: 'root'
})
export class QueryClient extends QueryCore {
  private options = inject(QUERY_CLIENT_OPTIONS);

  constructor() {
    super({
      ...options,
      defaultOptions: {
        ...options?.defaultOptions,
        queries: {
          staleTime: Infinity,
          ...options?.defaultOptions?.queries,
        },
      },
    });
  }
}
```

Haven't tested it tho, the electricity in my city went off

**Comment by tieppt** [comment]
Because QueryClient is an InjectorToken<QueryCore>, so you can use this one:

```ts
type UnwrapInjectionToken<TypeInjectionToken extends InjectionToken<unknown>> =
  TypeInjectionToken extends InjectionToken<infer Wrapped> ? Wrapped : unknown;

@Injectable({
  providedIn: 'root',
})
export class TodosService {
  // private http = inject(HttpClient);
  // private queryClient = inject(QueryClient);
  // private useQuery = inject(QueryProvider);
  // private useMutation = inject(MutationProvider);
  constructor(
    private http: HttpClient,
    @Inject(QueryClient)
    private queryClient: UnwrapInjectionToken<typeof QueryClient>,
    @Inject(QueryProvider)
    private useQuery: UnwrapInjectionToken<typeof QueryProvider>,
    @Inject(MutationProvider)
    private useMutation: UnwrapInjectionToken<typeof MutationProvider>
  ) {}

  getTodos() {
    return this.useQuery(['todos'], () => {
      return this.http.get<Todo[]>(
        'https://jsonplaceholder.typicode.com/todos'
      );
    });
  }

  addTodoOriginal() {
    return this.useMutation(({ title }: { title: string }) => {
      return this.http
        .post<Todo>(`https://jsonplaceholder.typicode.com/todos`, { title })
        .pipe(
          tap(() => {
            this.queryClient.invalidateQueries(['todos']);
          })
        );
    });
  }

  addTodoBuiltIn({ title }: { title: string }) {
    return this.http
      .post<Todo>(`https://jsonplaceholder.typicode.com/todos`, { title })
      .pipe(
        tap(() => {
          this.queryClient.invalidateQueries(['todos']);
        })
      );
  }

  getTodo(id: number) {
    return this.useQuery(['todo', id], () => {
      return this.http
        .get<Todo>(`https://jsonplaceholder.typicode.com/todos/${id}`)
        .pipe(delay(1000));
    });
  }
}

```

**Comment by Den-dp** [comment]
My misunderstanding was more about "why `InjectionToken` is used here?" and "why it can't be implemented a class?".

Now I realize that while `QueryClient` can be rewritten as an injectable class, but `MutationProvider`, `IsFetchingProvider`, `IsMutatingProvider`, `PersistedQueryProvider`, `InfiniteQueryProvider` - can not.

The reason for this is DX that this library tries to achieve.

`MutationProvider`, `IsFetchingProvider`, `IsMutatingProvider`, `PersistedQueryProvider`, `InfiniteQueryProvider` are meant to be used as function calls: `useMutation()`, `useIsFetching()`, `useIsMutating()`, `usePersistedQuery()`, `useInfiniteQuery()`. So, to provide a function-like experience they can't be implemented in other than `InjectionToken` way (classes aren't callable).

`QueryClient` is already a class so my code above might work without breaking the initial DX.

----

Overall, I'd like to see this library allowing the best DI experience for both worlds 🙌:
✔️ shiny new `inject()` based
🚫 safely typed constructor-based (so without `@Inject()` stuff and manual typing)

**Comment by NetanelBasal** [comment]
We can expose the class providers. The issue is naming.

**Comment by NetanelBasal** [comment]
This is my suggestion - https://github.com/ngneat/query/pull/51/files

**Comment by NetanelBasal** [comment]
Done
