### ISSUE TITLE
Rename QueryClient InjectionToken to QueryClientProvider

### ISSUE THREAD

**Issue by luii** [ngneat/query#50]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

No

### Description

I think it would wise to change the naming of the `QueryClient` InjectionToken to `QueryClientProvider`.
This way we can avoid the naming conflicts with the `QueryClient` in `@tanstack/query-core` package.

For now im importing both `QueryClient` types from `@ngneat/query` and `@tanstack/query-core` and rename the first one to get full verbose typing in my code

```typescript
import {QueryClient} from "@tanstack/query-core";
import {QueryClient as QueryClientProvider} from '@ngneat/query'

class A {
  private readonly _queryClient: QueryClient = inject(QueryClientProvider)
}
```

I think this also makes sense since the QueryClient exported by `@ngneat/query` is a Injection Token and not an instantiatable Class.

### Do you want to create a pull request?

No

**Comment by zarghamkhandev** [comment]
@NetanelBasal if you agree on this, I could create a PR.

**Comment by NetanelBasal** [comment]
Why do you need to import `QueryClient`? In your example, there is no need to strictly type the property.

**Comment by luii** [comment]
I know that there is no need to explicitly type it, but for an abstract service that will get extended by a couple of concrete services it would make sense when overriding the injection properties

**Comment by NetanelBasal** [comment]
I'd consider it as part of https://github.com/ngneat/query/issues/48#issuecomment-1305149248. We need to think about the naming convention.

**Comment by NetanelBasal** [comment]
This is my suggestion - https://github.com/ngneat/query/pull/51/files

**Comment by luii** [comment]
https://github.com/ngneat/query/pull/51/files#r1016233642

**Comment by NetanelBasal** [comment]
Renaming is done.
