### ISSUE TITLE
Auto Refetching example playground

### ISSUE THREAD

**Issue by JoaoPauloLousada** [ngneat/query#76]
### Description

Implement Auto Refetching example in playground.

### Proposed solution

Similar to this example:
https://tanstack.com/query/v4/docs/react/examples/react/auto-refetching

### Alternatives considered

None

### Do you want to create a pull request?

No

**Comment by JoaoPauloLousada** [comment]
Can I have this issue assigned to me, please?

**Comment by NetanelBasal** [comment]
Sure

**Comment by JoaoPauloLousada** [comment]
https://github.com/ngneat/query/pull/77
