### ISSUE TITLE
Optimistic updates example doesn't work

### ISSUE THREAD

**Issue by hichemfantar** [ngneat/query#84]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

Yes

### Description

The optimistic updates example in the demo doesn't work.
Clicking the button doesn't do anything.

### Please provide a link to a minimal reproduction of the bug

https://ngneat.github.io/query/optimistic-updates

### Do you want to create a pull request?

No

**Comment by JoaoPauloLousada** [comment]
can I have this issue assigned to me?

**Comment by JoaoPauloLousada** [comment]
https://github.com/ngneat/query/pull/86
