### ISSUE TITLE
Documentation navigation menu doesn't open on mobile

### ISSUE THREAD

**Issue by hichemfantar** [ngneat/query#85]
### Which @ngneat/query-* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Pressing the menu button does nothing.
![Screenshot_20230204-120836](https://user-images.githubusercontent.com/34947993/216763985-fcd2d07a-e05d-427a-a9a6-9bd905d2b58e.jpg)

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Don't relevant anymore in next version
