### ISSUE TITLE
`refetchOnWindowFocus` in module's providers doesn't have any effect

### ISSUE THREAD

**Issue by Londeren** [ngneat/query#88]
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

Yes

### Description

In my module I have:
```
providers: [
    provideQueryClientOptions({
      defaultOptions: {
        queries: {
          refetchOnWindowFocus: false,
        },
      },
    }),
  ],
```

Then I call `useQuery` in a component, that declared in this module:

```
…
this.useQuery(
  ['todo', id],
  () => this.http.getTodo({ id })
).result$
…
```

After switching between tabs new requests are called.
However, if I add `refetchOnWindowFocus` to `useQuery` itself, it works fine:
```
…
this.useQuery(
  ['todo', id],
  () => this.http.getTodo({ id }),
  { refetchOnWindowFocus: false }
).result$
…
```

### Please provide the environment you discovered this bug in

```true
Angular 15.1.3
```

### Do you want to create a pull request?

No

**Comment by luii** [comment]
Can you please provide a stackblitz or repository to reproduce your exact error?

Also which version of `@ngneat/query` are you using?
