### ISSUE TITLE
Implement QueriesProvider

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/query#9]
https://tanstack.com/query/v4/docs/reference/useQueries

**Comment by NetanelBasal** [comment]
combineLatest instead?

**Comment by hrvbernardic** [comment]
✋

**Comment by hrvbernardic** [comment]
I tried to find a problem we would solve by implementing **useQueries** but I just don't see it. Using combineLatest as you said by supplying multiple **useQuery** looks simple enough for me. In case I missed something, please tell me 😀.

**Comment by NetanelBasal** [comment]
Can you please add a new page and example to our playground?

**Comment by hrvbernardic** [comment]
Sure

**Comment by NetanelBasal** [comment]
@hrvbernardic, do you want to add more examples to our playground? https://github.com/ngneat/query/issues/30

**Comment by hrvbernardic** [comment]
@NetanelBasal sure I'll take something
