### ISSUE TITLE
Allow constructor injection for QueryClientService

### ISSUE THREAD

**Issue by GregOnNet** [ngneat/query#98]
Hi 👋🏻, 

thanks for working on this library. I really like the approach and the intuitive API.

Are there plans to support `constructor`-Injection for QueryClientService?
Currently, it does not work since it is an `InjectionToken`, which causes compilation errors (see images below).

Maybe `QueryClient` needs to be exposed as Public API.

## Pure Constructor DI

![image](https://github.com/ngneat/query/assets/444278/be61ce71-641c-4ac5-9c3e-7825880b6fb9)

## @Inject-DI

![image](https://github.com/ngneat/query/assets/444278/efae3769-20d1-46ea-9a0e-367992c38634)

**Comment by NetanelBasal** [comment]
The "use constructor DI" section in the readme doesn't work?

**Comment by GregOnNet** [comment]
Hi,

maybe I am missing something.

The `README` mentions.

```
QueryService.use(...)
PersistedQueryService.use(...)
InfiniteQueryService.use(...)
MutationService.use(...)
```

But the `QueryClientService` is not in the list.

Nevertheless, I tried to inject it this way, but then I get the Compiler Error.

![image](https://github.com/ngneat/query/assets/444278/e85dce7b-07f3-482c-a04b-8639ea2e11fb)

Also, `QueryClientService` is not being recognized of being used in the code.

![image](https://github.com/ngneat/query/assets/444278/5350d482-f5e4-4c35-bd4b-fe72e5bac2d7)

Thanks for your support

**Comment by luii** [comment]
I faced the same issue a months earlier, this is how i ended up solving this problem. Since the QueryClientService is just a Injection Token it need to use the `@Inject(...)` decorator in the constructor and to get typing you need to unwrap the injection token to get the type.

Consider the following:

```
// unwrap-injection-token.ts
export type UnwrapInjectionToken<T> = T extends InjectionToken<(infer U)> ? U : never;

....

// some-other-service.ts
public constructor(
  @Inject(QueryClientService) private readonly _queryClient: UnwrapInjectionToken<typeof QueryClientService>
) {}
```js

this should work and give you the correct typing.

**Comment by NetanelBasal** [comment]
That's correct. QueryClientService is not listed because it's a normal Injection Token.

**Comment by NetanelBasal** [comment]
You can use @luii suggestion:

```ts
export type UnwrapInjectionToken<T> = T extends InjectionToken<infer U>
  ? U
  : never;

export type QueryClient = UnwrapInjectionToken<typeof QueryClientService>;

@Inject(QueryClientService) private queryClient: QueryClient

```

**Comment by GregOnNet** [comment]
Hi,

thanks for the input.

In order to be able of injecting the `QueryClientService` without using `Inject`-Decorator, I created a provider for it.

## query-client.ts
Contains `QueryClient`-class that will be injected and holds the implentation of `QueryClientService`.

```ts

import { InjectionToken } from '@angular/core';
import { QueryClientService } from '@ngneat/query';

export type UnwrapInjectionToken<T> = T extends InjectionToken<infer U> ? U : never;

type QueryCore = UnwrapInjectionToken<typeof QueryClientService>;

/**
 *
 * Merges all members of QueryCore into QueryClient.
 * This is ok as long as QueryClient is setup via Angular's IoC-Container, because
 * QueryClient will get QueryClientService implementation.
 *
 */
export interface QueryClient extends QueryCore {}
export class QueryClient {}
```

## provide-ngneat-query-client.ts

Provider for `QueryClient`

```ts

import { FactoryProvider, inject } from '@angular/core';
import { QueryClientService } from '@ngneat/query';
import { QueryClient } from './query.client';

/**
 *
 * Allow to inject @ngneat/qeuery's QueryClientService with
 * Constructor DI.
 *
 * See https://github.com/ngneat/query/issues/98 for details.
 *
 */
export function provideNgNeatQueryClient(): FactoryProvider {
  return {
    provide: QueryClient,
    useFactory: () => inject(QueryClientService)
  };
}
```

## main.ts

```ts
bootstrapApplication(AppComponent, {
  providers: [
   // ...

    provideNgNeatQueryClient()
  ]
}).catch(err => console.error(err));
```

## Usage

```ts
@Injectable({  providedIn: 'root' })
export class SomeService {
  constructor(
    // ...
    private readonly queryClient: QueryClient,
  ) {}
}
```

Cheers
Gregor
